'''
Problem Link:- https://projecteuler.net/problem=2
Title:- Even Fibonacci Numbers
Problem Statement:- 
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''


def sum_of_even_fibonacci_numbers(n):
    sum = 0
    a = 1
    b = 2
    while b < n:
        if b % 2 == 0:
            sum += b
        a, b = b, a + b
    return sum

sum_of_even_fibonacci_numbers(4000000)